[:div, {class: "row"},
  [:h3, "System Information for #{host[:name]}"],

  [:div, {class: "col col-25"},
    [:h4, {class: "gra-subheading"}, "Machine Info"],
    [:div, {class: "gra-table-wrapper"},
      [:table, {class: "gra-table"}, 
        [:tr,
          [:th, "OS"],
          [:td, host[:os]]],
        [:tr,
          [:th, "Architecture"],
          [:td, host[:arch]]],
        [:tr,
          [:th, "Uptime"],
          [:td, host[:uptime]]],
        [:tr,
          [:th, "Boot Time"],
          [:td, Time.new(seconds: boot[:seconds], nanoseconds: 0, location: Time.local.location).to_s]]]]],

  [:div, {class: "col col-25"},
    [:h4, {class: "gra-subheading"}, "System Load"],
    [:div, {class: "gra-table-wrapper"},
      [:table, {class: "gra-table"},
        [:tr,
          [:th, "1m"],
          [:td, load[:load1].to_s],
          [:td, [show_bar(load[:load1] / (load[:load1] + load[:load5] + load[:load15]), "large", "red")]]],
        [:tr,
          [:th, "5m"],
          [:td, load[:load5].to_s],
          [:td, [show_bar(load[:load5] / (load[:load1] + load[:load5] + load[:load15]), "large", "yellow")]]],
        [:tr,
          [:th, "15m"],
          [:td, load[:load15].to_s],
          [:td, [show_bar(load[:load15] / (load[:load1] + load[:load5] + load[:load15]), "large", "yellow")]]]]]],

  [:div, {class: "col col-25"},
    [:h4, {class: "gra-subheading"}, "Memory Usage"],
    [:div, {class: "gra-table-wrapper"},
      [:table, {class: "gra-table"},
        [:tr,
          [:th, "Total: #{memory[:total_mb]} Mb"],
          [:td, "Used: #{memory[:used_mb]} Mb"],
          [:td, "Free: #{memory[:free_mb]} Mb"]]]],
    [show_arc(memory[:used_mb] / memory[:total_mb], "large", "green")]],

  [:div, {class: "col col-25"},
    [:h4, {class: "gra-subheading"}, "Net I/O"],
    [:div, {class: "gra-table-wrapper"},
      [:table, {class: "gra-table"},
        [:tr,
          [:th, "Upload (Mb)"],
          [:td, net[:sent_mb].to_s],
          [:td, [show_bar(net[:sent_mb] / (net[:sent_mb] + net[:received_mb]), "large", "blue")]]],
        [:tr,
          [:th, "Download (Mb)"],
          [:td, net[:received_mb].to_s],
          [:td, [show_bar(net[:received_mb] / (net[:sent_mb] + net[:received_mb]), "large", "blue")]]]]]],

  disks.sort_by {|d| d[:usage].to_f}.reverse.map do |disk|

    accent = case disk[:usage].to_f
      when .<= 25.0 then "blue"
      when .<= 50.0 then "green"
      when .<= 75.0 then "yellow"
      else "red"
    end
    
    [:div, {class: "col col-25"},
    	[:div, {class: "gra-card gra-card-horizontal gra-card-media-left"},
    		[:figure, {class: "gra-card-media-wrapper"},
    			[:div, {class: "gra-object-fit"},
    				[show_arc(disk[:usage].to_f, "large", accent)]]],
    		[:div, {class: "gra-card-content"},
    			[:h5, {class: "gra-card-title"}],
    			[:div, {class: "gra-card-body"},
            [:p,
              [:span, {class: "gra-bold-text"}, "Filesystem type: "],
              [:span, disk[:fstype]]],
            [:p,
              [:span, {class: "gra-bold-text"}, "Device: "],
              [:span, disk[:device]]],
            [:p,
              [:span, {class: "gra-bold-text"}, "Size (Mb): "],
              [:span, disk[:size_mb].to_s]],
            [:p,
              [:span, {class: "gra-bold-text"}, "Used (Mb): "],
              [:span, disk[:used_mb].to_s]],
            [:p,
              [:span, {class: "gra-bold-text"}, "Free (Mb): "],
              [:span, disk[:free_mb].to_s]],
            [:p,
              [:span, {class: "gra-bold-text"}, "Usage (%): "],
              [:span, disk[:usage].to_s]]]]]]

  end ]
