[:div, {class: "gauge-host"},
  [:h4, {class: "gra-subheading"}, "Machine Info"],
  [:div, {class: "gra-table-wrapper"},
    [:table, {class: "gra-table"}, 
      [:tr,
        [:th, "Hostname"],
        [:td, host.name]],
      [:tr,
        [:th, "OS"],
        [:td, "#{host.os} #{host.arch}"]],
      [:tr,
        [:th, "Uptime"],
        [:td, host.uptime]],
      [:tr,
        [:th, "Boot Time"],
        [:td, Time.unix(boot.seconds).to_s]]]]]
